apiVersion: v1
items:
- apiVersion: v1
  data:
    blog.txt: NWVjdXIzCg==
  kind: Secret
  metadata:
    creationTimestamp: "2025-02-23T08:00:04Z"
    name: blog
    namespace: default
    resourceVersion: "5161"
    uid: 79a87918-d594-4668-9628-7d494c2bccbf
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
