apiVersion: v1
kind: Pod
metadata:
  name: secret-datacenter
spec:
  volumes:
  - name: secret-datacenter-volume
    secret:
      secretName: blog
  containers:
  - name: secret-container-datacenter
    image: fedora:latest
    command: ["sleep", "50000"]
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secret-datacenter-volume
      mountPath: /opt/games
