apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: vote
spec:
  selector:
    app: redis-deployment
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
