apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: vote
spec:
  selector:
    app: result
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 80
      nodePort: 31001
  type: NodePort
