apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  selector:
    app: httpd-php-mysql
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30008
      targetPort: 80
