apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  storageClassName: manual  # 🛠️ Matches the PV’s storage class
  accessModes:
    - ReadWriteOnce  # ✏️ Matches PV’s access mode
  resources:
    requests:
      storage: 3Gi  # 📏 Requests 3Gi of storage from the PV
