apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: envars
spec:
  containers:
  - image: busybox:latest
    name: fieldref-container
    resources: {}
  dnsPolicy: ClusterFirst
  command: 
    - "sh"
    - "-c"
    - "while true; do echo -en '\n'; echo $NODE_NAME; echo $POD_NAME; echo $POD_SERVICE_ACCOUNT; sleep 10; done;"
  restartPolicy: Never
  env:
    - name: NODE_NAME
      valueFrom: 
        fieldRef: 
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom: 
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: POD_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
status: {}
